// import './Sales/index'
// import './ObserverPattern/index'
// import './DecoratorPattern/index'
// import './FactoryPattern/index'
// import './CommandPattern/index'
// import './AdapterPattern/index'
// import './FacadePattern/index'
// import './FlyweightPattern/index'
// import './TemplateMethodPattern/index'
// import './IteratorPattern/index'
// import './CompositePattern/index'
// import './StatePattern/index'
// import './ProxyPattern/index'
// import './CompoundPatterns/index'
import './Registry'
