// import './Sales/index'
// import './ObserverPattern/index'
// import './DecoratorPattern/index'
// import './FactoryPattern/index'
// import './CommandPattern/index'
// import './AdapterPattern/index'
// import './FacadePattern/index'
import './FlyweightPattern/index'
